version: '3.8'
services:
  ticket-service:
    container_name: ticket-service
    image: node:20-alpine
    volumes:
      - type: bind
        source: ./../
        target: /app
    mem_limit: 256m
    cpus: 1
    working_dir: /app
    command: npm run dev
    env_file:
      ./../.env
    ports:
      - '${PORT}:${PORT}'